#!/usr/bin/env node

/**
 * EmailJS Setup Helper
 * This script helps you configure EmailJS for your contact form
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('\n🚀 EmailJS Configuration Setup\n');
console.log('═'.repeat(50));
console.log('\n📧 This will set up your contact form to send real emails!\n');

console.log('First, you need to get your EmailJS credentials:');
console.log('1. Go to: https://www.emailjs.com/');
console.log('2. Sign up (or login if you have an account)');
console.log('3. Add an Email Service (Gmail recommended)');
console.log('4. Create an Email Template');
console.log('5. Get your API Keys\n');

console.log('═'.repeat(50));
console.log('\n🔑 Enter your EmailJS credentials:\n');

const questions = [
  {
    key: 'NEXT_PUBLIC_EMAILJS_SERVICE_ID',
    question: 'Service ID (e.g., service_abc123): ',
    hint: 'Found in: Email Services section'
  },
  {
    key: 'NEXT_PUBLIC_EMAILJS_TEMPLATE_ID',
    question: 'Template ID (e.g., template_xyz789): ',
    hint: 'Found in: Email Templates section'
  },
  {
    key: 'NEXT_PUBLIC_EMAILJS_PUBLIC_KEY',
    question: 'Public Key (e.g., aBcDeFgHiJkLmN): ',
    hint: 'Found in: Account > API Keys'
  }
];

const answers = {};
let currentQuestion = 0;

function askQuestion() {
  if (currentQuestion >= questions.length) {
    createEnvFile();
    return;
  }

  const q = questions[currentQuestion];
  console.log(`\n📝 ${q.hint}`);
  rl.question(q.question, (answer) => {
    if (!answer.trim()) {
      console.log('❌ This field is required. Please try again.');
      askQuestion();
      return;
    }
    
    answers[q.key] = answer.trim();
    currentQuestion++;
    askQuestion();
  });
}

function createEnvFile() {
  const envPath = path.join(__dirname, '.env.local');
  
  const envContent = `# EmailJS Configuration
# Generated by setup-email.js on ${new Date().toISOString()}

# Your EmailJS Service ID
${answers.NEXT_PUBLIC_EMAILJS_SERVICE_ID ? `NEXT_PUBLIC_EMAILJS_SERVICE_ID=${answers.NEXT_PUBLIC_EMAILJS_SERVICE_ID}` : 'NEXT_PUBLIC_EMAILJS_SERVICE_ID=service_xxxxxxx'}

# Your EmailJS Template ID
${answers.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID ? `NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=${answers.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID}` : 'NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=template_xxxxxxx'}

# Your EmailJS Public Key
${answers.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY ? `NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=${answers.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY}` : 'NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=xxxxxxxxxxxxxxxx'}

# IMPORTANT: Never commit this file to git (it's in .gitignore)
# Contact form will send emails to: sathis.rc.dev@gmail.com
`;

  try {
    fs.writeFileSync(envPath, envContent);
    console.log('\n✅ Success! .env.local file created!\n');
    console.log('═'.repeat(50));
    console.log('\n📋 Configuration Summary:\n');
    console.log(`Service ID:  ${answers.NEXT_PUBLIC_EMAILJS_SERVICE_ID || 'Not set'}`);
    console.log(`Template ID: ${answers.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID || 'Not set'}`);
    console.log(`Public Key:  ${answers.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY || 'Not set'}`);
    console.log('\n═'.repeat(50));
    console.log('\n🎯 Next Steps:\n');
    console.log('1. Restart your development server:');
    console.log('   npm run dev\n');
    console.log('2. Test your contact form:');
    console.log('   http://localhost:3000/contact\n');
    console.log('3. Check your email inbox for test messages!\n');
    console.log('═'.repeat(50));
    console.log('\n✨ Your contact form is ready to send real emails! 🎉\n');
  } catch (error) {
    console.error('\n❌ Error creating .env.local file:', error.message);
    console.log('\n💡 Manual Setup:');
    console.log('1. Create a file named .env.local in your project root');
    console.log('2. Copy this content:\n');
    console.log(envContent);
  }

  rl.close();
}

// Check if user wants to skip interactive mode
if (process.argv.includes('--manual')) {
  console.log('\n📖 Manual Setup Mode\n');
  console.log('Create a file named .env.local in your project root with:\n');
  console.log(`NEXT_PUBLIC_EMAILJS_SERVICE_ID=your_service_id
NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=your_template_id
NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=your_public_key
`);
  console.log('\nReplace the values with your actual EmailJS credentials.');
  console.log('Get them from: https://dashboard.emailjs.com/\n');
  process.exit(0);
}

// Start interactive setup
console.log('💡 Press Ctrl+C to exit anytime\n');
console.log('Don\'t have an EmailJS account yet?');
console.log('→ Run: node setup-email.js --manual\n');

setTimeout(() => {
  rl.question('Ready to start? (yes/no): ', (answer) => {
    if (answer.toLowerCase() === 'yes' || answer.toLowerCase() === 'y') {
      askQuestion();
    } else {
      console.log('\n👋 Setup cancelled. Run this script again when ready!');
      console.log('Or run: node setup-email.js --manual\n');
      rl.close();
    }
  });
}, 100);

